{
  'variables' : {
    'shared_include_dirs' : [
      'src',
      'node_modules/windows-angle/deps/angle/include',
      'node_modules/windows-angle/src/shim',
      'external/skia/include',
      "<!(node -e \"require('nan')\")",
      'external/skia/include/android',
      'external/skia/include/animator',
      'external/skia/include/codec',
      'external/skia/include/config',
      'external/skia/include/core',
      'external/skia/include/effects',
      'external/skia/include/gpu',
      'external/skia/include/images',
      'external/skia/include/pathops',
      'external/skia/include/ports',
      'external/skia/include/private',
      'external/skia/include/svg',
      'external/skia/include/utils',
      'external/skia/include/views',
      'external/skia/include/xml',
      'external/skia/src/core'
    ],
    # TODO: proper Debug/Release support
    'shared_static_libraries': [
      '../external/skia/out/Debug/libgenperf_libs.a',
      '../external/skia/out/Debug/libjpeg-turbo.a',
      '../external/skia/out/Debug/libpng_static.a',
      '../external/skia/out/Debug/libskia_codec.a',
      '../external/skia/out/Debug/libskia_codec_android.a',
      '../external/skia/out/Debug/libskia_core.a',
      '../external/skia/out/Debug/libskia_effects.a',
      '../external/skia/out/Debug/libskia_images.a',
      '../external/skia/out/Debug/libskia_opts.a',
      '../external/skia/out/Debug/libskia_opts_sse41.a',
      '../external/skia/out/Debug/libskia_opts_ssse3.a',
      '../external/skia/out/Debug/libskia_ports.a',
      '../external/skia/out/Debug/libskia_sfnt.a',
      '../external/skia/out/Debug/libskia_skgpu.a',
      '../external/skia/out/Debug/libskia_utils.a',
      '../external/skia/out/Debug/libwebp_dec.a',
      '../external/skia/out/Debug/libwebp_demux.a',
      '../external/skia/out/Debug/libwebp_dsp.a',
      '../external/skia/out/Debug/libwebp_enc.a',
      '../external/skia/out/Debug/libwebp_utils.a'
    ]
  },
}
